<a href="https://colab.research.google.com/github/AzlinRusnan/Python-Coding/blob/main/Azlin_Learn_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Load numpy library
import numpy as np


In [5]:
#A Python List

L = list(range(10))
print(L)
type(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [6]:
#The item in c originally is integer
#because of the str() function, it is changed to string data type

L2 = [str(c) for c in L]
print(L2)

#Data type for L2
print(type(L2))
print(type(L2[2]))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'list'>
<class 'str'>


In [7]:
# Heterogeneous data type

L3 = [True, "2m", 3.0, 4]

#want to check for each element in the list
[type(item) for item in L3]

[bool, str, float, int]

In [8]:
# Creating array from python lists

# create arrays from NumPy lists
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [9]:
# NumPy is constrained to arrays that all contain the same data type.
# Integers are upcast to floating point! #[4,3.4], 4 will be float as well
np.array([3.14,5,9,111])

array([  3.14,   5.  ,   9.  , 111.  ])

In [10]:
# set explicitly the data type we want
np.array([1,2,3,4], dtype = 'float32') #32 is 32 byte

array([1., 2., 3., 4.], dtype=float32)

In [11]:
#Exercise 2: Creating Arrays from Scratch
# Create a length-10 integer array filled with zeros
np.zeros(10,dtype = int) #10 = is how many zeros you want to create
np.zeros(10,dtype = 'float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [12]:
#Exercise 3: Create a 3 x 5 floating-point array filled with ones
# create a 3x5 array
np.ones((3,5), dtype = str) #3 row, 5 col

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [13]:
#Exercise 4: Create a 3 x 5 array filled with 3.14
#create a 3x4 array
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
new_array = np.full((3,3),2)
new_array

existing_array = np.array([[1,1,1],[1,1,1],[1,1,1]])
existing_array[:] = 2
existing_array

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [15]:
# Exercise 5: Create an array filled with linear sequence
# Create an array filled with linear sequence
# Starting at 0, ending at 20 (excluding), skipping by 2
# np.arange(start, stop, step)

#start: The starting value of the sequence (inclusive). If you omit this parameter, it defaults to 0.
#stop: The end value of the sequence (exclusive). The array values will go up to but not include this value.
#step: The difference between each value in the array. If you omit this parameter, it defaults to 1.

np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [16]:
# Exercise 6: Create an array evenly spaced values
# linspace() - generates linearly spaced vectors
# Create an array of five values evenly spaced between 0 and 1
# linspace - generates linearly spaced vectors

np.linspace(0,1,8)

#cara kira dia mcm ni,
# 1-0
# Since there are 8 elements, the range is divided into 7 equal intervals (note that there are always num - 1 intervals).
#1/7 = 0.1428714

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [17]:
# Exercise 7: Create a 3 x 3 uniformly distributed array
# Random values between 0 and 1

np.random.random((3,3))

#random and did not seed number

array([[0.35541361, 0.37705824, 0.93425182],
       [0.6976339 , 0.21394359, 0.69128905],
       [0.82102204, 0.41214436, 0.98437939]])

In [18]:
# Exercise 8: Create a 3 x 3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

#note that (3,3) is row and column

array([[-1.72600503,  0.50195599,  1.59174731],
       [-1.60640007, -1.29793201, -0.61589696],
       [-1.70567307, -0.09017643, -0.85160421]])

In [19]:
#Exercise 9: Create a 3x3 array of random integers in the interval [0, 10)
#"[ ]" is inclusive
#"( )" is exclusive

# Create a 3x3 array of random integers in the interval [0, 10)
#0 until 9 only
#str also can have this

np.random.randint(0,10,(3,3))

array([[5, 5, 8],
       [7, 0, 3],
       [2, 0, 0]])

In [20]:
# Use random.uniform() function to create random float number

np.random.uniform(0,5,(3,3))

array([[4.7642699 , 4.09529097, 0.55661144],
       [4.42806344, 3.48282123, 4.11537269],
       [4.83736765, 2.15123406, 1.65793513]])

In [21]:
import pandas as pd
srs_a = pd.Series([10,30,60,80,90])
srs_b = pd.Series(['red', 'gree','blue','white','black'])
df = pd.DataFrame({'a': srs_a, 'b': srs_b})
df

a      b
0  10    red
1  30   gree
2  60   blue
3  80  white
4  90  black

In [ ]:
#from above table
#axis0 - looking at rowwise {adding data vertically} |
#axis1 - looking at columnwise {data added horizontaly} ----

In [22]:
# NumPy Array Attributes
np.random.seed(1957)

x1 = np.random.randint(10,size = 6) #1D array
x2 = np.random.randint(10, size = (3,4)) #2D array
x3 = np.random.randint(10, size = (3,4,5)) #3D array

In [23]:
x1

array([9, 1, 7, 4, 7, 2])

In [24]:
x2

array([[0, 4, 5, 7],
       [7, 7, 2, 4],
       [7, 1, 2, 0]])

In [25]:
x3

array([[[9, 3, 3, 4, 3],
        [0, 0, 9, 1, 5],
        [7, 6, 0, 8, 1],
        [7, 3, 8, 3, 3]],

       [[2, 1, 2, 2, 6],
        [8, 4, 1, 3, 7],
        [0, 2, 1, 2, 6],
        [3, 8, 3, 6, 4]],

       [[9, 4, 2, 9, 6],
        [8, 7, 8, 8, 7],
        [0, 6, 4, 4, 2],
        [2, 9, 7, 5, 7]]])

In [26]:
# Each array has attributes ndim() (the number of dimensions), shape() (the size of each dimension), and size() (the total size of the array)
# Check attributes of the array x3
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size) # 3x4x5=60

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [27]:
# Exercise 13: Array Indexing: Accessing Single Elements
# Output the list
x1

array([9, 1, 7, 4, 7, 2])

In [28]:
# Accessing single element
x1[3]

4

In [29]:
# Accessing single element: : Negative indexing
x1[-3]

4

In [30]:
# Output x2 list
x2

array([[0, 4, 5, 7],
       [7, 7, 2, 4],
       [7, 1, 2, 0]])

In [34]:
# Acessing single element in 2D array
x2[0,3]

7

In [35]:
# Acessing single element in 2D array: using negative indexing
x2[-1,-2]

2

In [36]:
# Change the value in 2D array
# change the number 2 to 32
x2[1,2] = 32
x2

array([[ 0,  4,  5,  7],
       [ 7,  7, 32,  4],
       [ 7,  1,  2,  0]])

In [37]:
# Acessing single element in 2D array
x2[0,3]

7

In [ ]:
x1

array([9, 1, 7, 4, 7, 2])

In [ ]:
# NumPy arrays have a fixed type
# Inserting a floating-point value to an integer array will be silently truncated
x1[0] = 3.1415
x1


numpy.ndarray

In [ ]:
import numpy as np

In [ ]:
# NumPy arange - array range
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# NumPy indexing
x[4:7]
print(x[4:7])

# Every other element
x[::4] #skiping by 4
print(x[::4])

# Every other element, starting at index 1
x[1::2]
print(x[1::2])

# All elements, reversed
x[::-2]
print(x[::-2])

# Reversed every other from index 5
x[5::-2]
print(x[5::-2])
x[-5::-2]
print(x[-5::-2])

[4 5 6]
[0 4 8]
[1 3 5 7 9]
[9 7 5 3 1]
[5 3 1]
[5 3 1]


In [38]:
# Exercise 15: Multi-dimensional subarrays

# Multi-dimensional subarrays
np.random.seed(1957)
x2 = np.random.randint(10, size = (3,4)) #2D array
print(x2)

print("\n")

print(x2[1:3])
print(x2[1:3,1:3])

print("\n")

# 2D array indexing, skip of two
print(x2[:3,::2])

print("\n")

# Everything reverse
print(x2[:3,::-1])



[[9 1 7 4]
 [7 2 0 4]
 [5 7 7 7]]


[[7 2 0 4]
 [5 7 7 7]]
[[2 0]
 [7 7]]


[[9 7]
 [7 0]
 [5 7]]


[[4 7 1 9]
 [4 0 2 7]
 [7 7 7 5]]


In [39]:
#inverse
print(x2)
print("\n")
print(x2[::-1,])
print("\n")
print(x2[::-1,::-1])

#::-1 for Rows: The first ::-1 applies to the rows of the array. It reverses the order of the rows. In simple terms, it starts from the last row and ends at the first row, stepping backward.

#::-1 for Columns: The second ::-1 applies to the columns. It reverses the order of the columns in each row, starting from the last column to the first, also stepping backward.

[[9 1 7 4]
 [7 2 0 4]
 [5 7 7 7]]


[[5 7 7 7]
 [7 2 0 4]
 [9 1 7 4]]


[[7 7 7 5]
 [4 0 2 7]
 [4 7 1 9]]


In [40]:
#Accessing array rows and columns
print(x2)
print("\n")
# first column of x2
x2[:,:1]
#x2[:3,:1]
#x2[:3,0]

[[9 1 7 4]
 [7 2 0 4]
 [5 7 7 7]]




array([[9],
       [7],
       [5]])

In [41]:
# first row of x2
print(x2)
print("\n")

print(x2[:1,]) #extract the data in 2D, the o/p will have double quotation
print(x2[0])

[[9 1 7 4]
 [7 2 0 4]
 [5 7 7 7]]


[[9 1 7 4]]
[9 1 7 4]


In [42]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [43]:
#Subarrays as no-copy views
print(x2)

print("\n")

#extract certain data
x2_sub = x2[:2,:2]
print(x2_sub)

print("\n")



[[9 1 7 4]
 [7 2 0 4]
 [5 7 7 7]]


[[9 1]
 [7 2]]




In [44]:
#substitute 0 in x2_sub to value 99
x2[1:2,2:3] = 99
print(x2)

[[ 9  1  7  4]
 [ 7  2 99  4]
 [ 5  7  7  7]]


In [45]:
#Creating copies of arrays
## Explicitly copy the data within an array
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

print("\n")

#change the value 99 to 1957
x2_sub_copy[0,0] = 1957
print(x2_sub_copy)

print("\n")
# The original array stays intact!
print(x2)

[[9 1]
 [7 2]]


[[1957    1]
 [   7    2]]


[[ 9  1  7  4]
 [ 7  2 99  4]
 [ 5  7  7  7]]


In [50]:
# Reshaping of Arrays
# NumPy arange
x = np.arange(1,10)
print(x)

print("\n")

# Put the numbers 1 through 9 in a 3×3 grid
# reshape
grid = np.arange(1,10).reshape(3,3)
print(grid)

[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
# Create NumPy array
x = np.array([1,2,3])
print(x)

print("\n")

# Reshape to array of 1 x 3
np.array([1,2,3]).reshape(3,1)

[1 2 3]




array([[1],
       [2],
       [3]])

In [52]:
# newaxis - bumped 1D array to 2D array

# From 1D array to 1x3 array on the row axis
# np.newaxis is used to add a new axis to the array
# In the context of a 1D array, it effectively converts it into a 2D row vector

x[np.newaxis, :]
print("\n")
# 3 x 1 array
x.reshape(3,1)

# bumped to 2D array on the column axis
# original is 1D array
# becomes 3 x 1 array
print(x)
print('\n--------------\n')
x[:, np.newaxis]



[1 2 3]

--------------



array([[1],
       [2],
       [3]])

In [53]:
# Array Concatenation and Splitting
# Concatenation of 1D arrays
# concatenate sambung
# splitting pecah

x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x,y]))

print('\n--------------\n')

# Concatenate
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([99,99,99])
print(np.concatenate([x,y,z]))

print('\n--------------\n')

# Two-dimensional arrays
# put in the variable named grid
grid = np.array([[1,2,3],[4,5,6]])
print(grid)

print('\n--------------\n')

# concatenate along the first axis
np.concatenate([grid,grid])

[1 2 3 3 2 1]

--------------

[ 1  2  3  3  2  1 99 99 99]

--------------

[[1 2 3]
 [4 5 6]]

--------------



array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#! axis = 0 -> running vertically downwards across rows |
#! axis = 1 -> running horizontally across columns ----

In [54]:
# Output grid
print(grid)

print("\n")

# Concatenate along the axis
# axis = 0 -> running vertically downwards across rows
# axis = 1 -> running horizontally across columns
#np.concatenate([grid,grid])
np.concatenate([grid,grid], axis = 1)

print("\n")

# Vertically stack the arrays
x = np.array([1,2,3])
y = np.array([[9,8,7],
             [6,5,4]])

np.vstack([x,y])
#vstack=stacking data vertically

[[1 2 3]
 [4 5 6]]






array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [55]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
#Splitting of arrays - opposite of concatenation
# Passing a list of indices giving the split points
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5]) #0,1,2,
print(x1,x2,x3)

#Here's what happens in the split:

#The first split happens before the index 3, so x1 will contain the elements from the start of x up to (but not including) the element at index 3. Therefore, x1 will be [1, 2, 3].
#The second split happens before the index 5, so x2 will contain the elements from index 3 up to (but not including) the element at index 5. Therefore, x2 will be [99, 99].
#Finally, x3 will contain the remaining elements of the array, which are [3, 2, 1].

[1 2 3] [99 99] [3 2 1]


In [59]:
# Create a 4 x 4 array
# use np.arange() and reshape()
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
# Vertical split
# use np.vsplit()
upper, lower = np.vsplit(grid, [3]) # [3]refering to the row index
print(upper)
print("\n---------------\n")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

---------------

[[12 13 14 15]]


In [63]:
print(grid)

print("\n")

# horizontal split
left, right = np.hsplit(grid, [2])
print(left)
print("\n---------------\n")
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

---------------

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
# TGK BALIK RECIPROCAL,Measure the execution time!!

In [67]:
# Element-wise division
# must have the same range of data

np.arange(5) / np.arange(1,6)
print(np.arange(5))
print("\n-----------------------\n")
print(np.arange(1,6))
np.arange(5) / np.arange(1,6)
print("\n-----------------------\n")

# Power of two
x = np.arange(9).reshape(3,3)
2 ** x

[0 1 2 3 4]

-----------------------

[1 2 3 4 5]

-----------------------



array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [72]:
# Array arithmetic
# // floor division -> rounds down to the nearest whole number
x = np.arange(4)
print("x // 2 = ", x // 2)

print("\n-----------\n")
# Array arithmetic
# nilai bahagi
x % 2

# Array arithmetic
print(x)
print("\n-----------\n")
-(0.5 * x + 1)**2
print("\n")

# Array arithmetic
print(x)
print("\n-----------\n")
np.add(x,2)

print("\n")
# Absolute value
x = np.array([-2,-1,0,1,2])
np.abs(x)

x // 2 =  [0 0 1 1]

-----------

[0 1 2 3]

-----------



[0 1 2 3]

-----------





array([2, 1, 0, 1, 2])

In [ ]:
# tgk balik time it