<a href="https://colab.research.google.com/github/AzlinRusnan/Python-Coding/blob/main/Azlin_Learn_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Load numpy library
import numpy as np


In [5]:
#A Python List

L = list(range(10))
print(L)
type(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [8]:
#The item in c originally is integer
#because of the str() function, it is changed to string data type

L2 = [str(c) for c in L]
print(L2)

#Data type for L2
print(type(L2))
print(type(L2[2]))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'list'>
<class 'str'>


In [9]:
# Heterogeneous data type

L3 = [True, "2m", 3.0, 4]

#want to check for each element in the list
[type(item) for item in L3]

[bool, str, float, int]

In [10]:
# Creating array from python lists

# create arrays from NumPy lists
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [11]:
# NumPy is constrained to arrays that all contain the same data type.
# Integers are upcast to floating point! #[4,3.4], 4 will be float as well
np.array([3.14,5,9,111])

array([  3.14,   5.  ,   9.  , 111.  ])

In [12]:
# set explicitly the data type we want
np.array([1,2,3,4], dtype = 'float32') #32 is 32 byte

array([1., 2., 3., 4.], dtype=float32)

In [14]:
#Exercise 2: Creating Arrays from Scratch
# Create a length-10 integer array filled with zeros
np.zeros(10,dtype = int) #10 = is how many zeros you want to create
np.zeros(10,dtype = 'float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [18]:
#Exercise 3: Create a 3 x 5 floating-point array filled with ones
# create a 3x5 array
np.ones((3,5), dtype = str) #3 row, 5 col

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [20]:
#Exercise 4: Create a 3 x 5 array filled with 3.14
#create a 3x4 array
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [26]:
new_array = np.full((3,3),2)
new_array

existing_array = np.array([[1,1,1],[1,1,1],[1,1,1]])
existing_array[:] = 2
existing_array

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [27]:
# Exercise 5: Create an array filled with linear sequence
# Create an array filled with linear sequence
# Starting at 0, ending at 20 (excluding), skipping by 2
# np.arange(start, stop, step)

#start: The starting value of the sequence (inclusive). If you omit this parameter, it defaults to 0.
#stop: The end value of the sequence (exclusive). The array values will go up to but not include this value.
#step: The difference between each value in the array. If you omit this parameter, it defaults to 1.

np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [28]:
# Exercise 6: Create an array evenly spaced values
# linspace() - generates linearly spaced vectors
# Create an array of five values evenly spaced between 0 and 1
# linspace - generates linearly spaced vectors

np.linspace(0,1,8)

#cara kira dia mcm ni,
# 1-0
# Since there are 8 elements, the range is divided into 7 equal intervals (note that there are always num - 1 intervals).
#1/7 = 0.1428714

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [29]:
# Exercise 7: Create a 3 x 3 uniformly distributed array
# Random values between 0 and 1

np.random.random((3,3))

#random and did not seed number

array([[0.15045955, 0.29271675, 0.54781692],
       [0.46986648, 0.4669327 , 0.24680777],
       [0.5794631 , 0.72941518, 0.52328194]])

In [31]:
# Exercise 8: Create a 3 x 3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

#note that (3,3) is row and column

array([[-1.52308994, -0.2853723 , -0.63810735],
       [ 0.19557789,  0.59397933,  3.06553295],
       [ 0.88643359, -1.59331247, -0.08875029]])

In [35]:
#Exercise 9: Create a 3x3 array of random integers in the interval [0, 10)
#"[ ]" is inclusive
#"( )" is exclusive

# Create a 3x3 array of random integers in the interval [0, 10)
#0 until 9 only
#str also can have this

np.random.randint(0,10,(3,3))

array([[0, 2, 9],
       [6, 6, 9],
       [4, 5, 3]])

In [37]:
# Use random.uniform() function to create random float number

np.random.uniform(0,5,(3,3))

array([[2.11124384, 0.92996424, 2.67800785],
       [1.6906161 , 1.29407279, 1.49032919],
       [3.29280962, 0.25377232, 0.19294997]])

In [39]:
import pandas as pd
srs_a = pd.Series([10,30,60,80,90])
srs_b = pd.Series(['red', 'gree','blue','white','black'])
df = pd.DataFrame({'a': srs_a, 'b': srs_b})
df

a      b
0  10    red
1  30   gree
2  60   blue
3  80  white
4  90  black

In [ ]:
#from above table
#axis0 - looking at rowwise {adding data vertically} |
#axis1 - looking at columnwise {data added horizontaly} ----

In [47]:
# NumPy Array Attributes
np.random.seed(1957)

x1 = np.random.randint(10,size = 6) #1D array
x2 = np.random.randint(10, size = (3,4)) #2D array
x3 = np.random.randint(10, size = (3,4,5)) #3D array

In [43]:
x1

array([9, 1, 7, 4, 7, 2])

In [44]:
x2

array([[0, 4, 5, 7],
       [7, 7, 2, 4],
       [7, 1, 2, 0]])

In [45]:
x3

array([[[9, 3, 3, 4, 3],
        [0, 0, 9, 1, 5],
        [7, 6, 0, 8, 1],
        [7, 3, 8, 3, 3]],

       [[2, 1, 2, 2, 6],
        [8, 4, 1, 3, 7],
        [0, 2, 1, 2, 6],
        [3, 8, 3, 6, 4]],

       [[9, 4, 2, 9, 6],
        [8, 7, 8, 8, 7],
        [0, 6, 4, 4, 2],
        [2, 9, 7, 5, 7]]])

In [48]:
# Each array has attributes ndim() (the number of dimensions), shape() (the size of each dimension), and size() (the total size of the array)
# Check attributes of the array x3
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size) # 3x4x5=60

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [49]:
# Exercise 13: Array Indexing: Accessing Single Elements
# Output the list
x1

array([9, 1, 7, 4, 7, 2])

In [50]:
# Accessing single element
x1[3]

4

In [51]:
# Accessing single element: : Negative indexing
x1[-3]

4

In [52]:
# Output x2 list
x2

array([[0, 4, 5, 7],
       [7, 7, 2, 4],
       [7, 1, 2, 0]])

In [53]:
# Acessing single element in 2D array
x2[0,3]

7

In [54]:
# Acessing single element in 2D array: using negative indexing
x2[-1,-2]

2

In [55]:
# Change the value in 2D array
# change the number 2 to 32
x2[1,2] = 32
x2

array([[ 0,  4,  5,  7],
       [ 7,  7, 32,  4],
       [ 7,  1,  2,  0]])

In [56]:
# Acessing single element in 2D array
x2[0,3]

7

In [58]:
x1

array([9, 1, 7, 4, 7, 2])

In [60]:
# NumPy arrays have a fixed type
# Inserting a floating-point value to an integer array will be silently truncated
x1[0] = 3.1415
x1


numpy.ndarray